sudo: required
dist: trusty
language: ruby

before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: O6ldTISpWYmnImraCDefLmNwF/Ig6N3VCa0vYA4i+RiJLykAFKgvG8N3JMJdRSoBPXpEvFJLk8Ct53EJZalUUjvUSdWQb3cmv0jySwwb5Et0QYWFyfF/q/YAp3mBvpydnLo3e+5A49J86ZXwdyq8EnybWjwIOkiKF4mURUyjapzU1E1N/6oGu7OKcdCwtU7X1mNb7i+TWqNrSAE/gCpS4RLRGX6VConnhgvQiMEmRShpboKf5eFnycKF5WMaXxbKglt1lnVtXpUo5KGiVKXKL1sc0b4TjYQNKwb6Ef+DIyrzQlfvauBs2Ti84aBFBphBWvl12e07MJ7npZ67gKyE3FCWBEO+YqRRH+BqlDfnhEyctrLH5IVApXpUUODyNUr9KA6tZdLA9LFHW4kiTPtrjW5r2zHsRcWwm/aA9k64CFq77Knzui4MzfOcxRxq5C4n5h4eyFejMkCNXT6kRTpzAHneHHqCRzqsDHiU48vGnBJOMPHPz2PEJQj4KZNzPjoEqKNsQDVfsbp3DEIPh4tDOu/VgSjYgL05E9TqgW+8KwI34EMoZmkyBKfQq982xh8JfKHUcgWvY5Dj4eT5Mfd/DxblDJbp6Ew/BbWSkPt97r7t6KvTD/QfKSBtkHYhGJIH9kR5uM53VNXPd+cm3uxDzQGr9mf13Mc8tUZ6yRsN9v4=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  on:
    repo: GITenberg/The-History-of-Don-Quixote-Volume-1-Part-08_5910
    tags: true
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy